<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>org.asynchttpclient</groupId>
    <artifactId>async-http-client-project</artifactId>
    <version>2.12.3</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>async-http-client</artifactId>
  <name>Asynchronous Http Client</name>
  <description>The Async Http Client (AHC) classes.</description>

  <properties>
    <javaModuleName>org.asynchttpclient.client</javaModuleName>
  </properties>

  <build>
    <testSourceDirectory>${project.basedir}/${test.dir}/test/java</testSourceDirectory>
    <directory>${project.basedir}/${target.dir}/</directory>
    <plugins>
      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <version>1.9.8</version>
          <configuration>
          <threads>16</threads>

          <timeoutConstant>8000</timeoutConstant>
          <mutators>
            <mutator>STRONGER</mutator>
          </mutators>
          <avoidCallsTo>
            <avoidCallsTo>java.*</avoidCallsTo>
            <avoidCallsTo>org.apache.log4j</avoidCallsTo>
            <avoidCallsTo>org.slf4j.*</avoidCallsTo>
            <avoidCallsTo>org.apache.commons.logging</avoidCallsTo>
          </avoidCallsTo>
          <verbose>false</verbose>
          <targetClasses>
            <param>org.asynchttpclient*</param>
          </targetClasses>
          <targetTests>
            <param>org.asynchttpclient.*</param>
          </targetTests>
            <excludedTestClasses>
              <param>org.asynchttpclient.AsyncStreamHandlerTest</param>
            </excludedTestClasses>
          <fullMutationMatrix>true</fullMutationMatrix>
          <exportLineCoverage>true</exportLineCoverage>
          <outputFormats>XML</outputFormats>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>test-jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.19.1</version>
        <configuration>
          <properties>
            <property>
              <name>junit</name>
              <value>false</value>
            </property>
          </properties>
          <excludes>
                <exclude>**/AsyncStreamHandlerTest.*</exclude>
              </excludes>
          <redirectTestOutputToFile>${surefire.redirectTestOutputToFile}</redirectTestOutputToFile>
          <systemPropertyVariables>
            <org.asynchttpclient.shutdownQuietPeriod>10</org.asynchttpclient.shutdownQuietPeriod>
            <org.asynchttpclient.shutdownTimeout>100</org.asynchttpclient.shutdownTimeout>
            <sun.net.spi.nameservice.nameservers>8.8.8.8</sun.net.spi.nameservice.nameservers>
            <sun.net.spi.nameservice.provider.1>dns,sun</sun.net.spi.nameservice.provider.1>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.asynchttpclient</groupId>
      <artifactId>async-http-client-netty-utils</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-codec-http</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-codec-socks</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler-proxy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-epoll</artifactId>
      <classifier>linux-x86_64</classifier>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-kqueue</artifactId>
      <classifier>osx-x86_64</classifier>
    </dependency>
    <dependency>
      <groupId>org.reactivestreams</groupId>
      <artifactId>reactive-streams</artifactId>
    </dependency>
    <dependency>
      <groupId>com.typesafe.netty</groupId>
      <artifactId>netty-reactive-streams</artifactId>
    </dependency>
    <dependency>
      <groupId>io.reactivex.rxjava2</groupId>
      <artifactId>rxjava</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.reactivestreams</groupId>
      <artifactId>reactive-streams-examples</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.kerby</groupId>
      <artifactId>kerb-simplekdc</artifactId>
      <scope>test</scope>
    </dependency>

        <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <version>6.14.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>30.1.1-jre</version>
      <scope>test</scope>
    </dependency>
  </dependencies>


  <profiles>
  <!-- Profile to build and run PerformanceTest. Use 'mvn test -Pjdk-rt' -->
  <profile>
    <id>testID</id>
    <activation>
      <property>
        <name>test.dir</name>
      </property>
    </activation>
  </profile>
  <profile>
    <id>targetID</id>
    <activation>
      <property>
        <name>target.dir</name>
      </property>
    </activation>
  </profile>
  </profiles>
</project>
