<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>org.asynchttpclient</groupId>
    <artifactId>async-http-client-project</artifactId>
    <version>2.12.3</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>async-http-client</artifactId>
  <name>Asynchronous Http Client</name>
  <description>The Async Http Client (AHC) classes.</description>

  <properties>
    <javaModuleName>org.asynchttpclient.client</javaModuleName>
  </properties>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>test-jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>2.19.1</version>
  <configuration>
    <excludes>
      <exclude>**/AsyncStreamHandlerTest.java</exclude>
            <exclude>**/ReactiveStreamsTest.java</exclude>
      <exclude>**/WebdavTest.java</exclude>
          <exclude>**/ProxyTest.java</exclude>

    </excludes>
  </configuration>
</plugin>

      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <version>1.22.0</version>

              <dependencies>
        <dependency>
          <groupId>org.pitest</groupId>
          <artifactId>pitest-testng-plugin</artifactId>
          <version>1.0.0</version>
        </dependency>
      </dependencies>


        <configuration>
        <testPlugin>testng</testPlugin>
          <threads>8</threads>
          <timeoutConstant>1000</timeoutConstant>
          <mutators>
            <mutator>STRONGER</mutator>
          </mutators>
          <avoidCallsTo>
            <avoidCallsTo>java.*</avoidCallsTo>
            <avoidCallsTo>org.apache.log4j</avoidCallsTo>
            <avoidCallsTo>org.slf4j.*</avoidCallsTo>
            <avoidCallsTo>org.apache.commons.logging</avoidCallsTo>
          </avoidCallsTo>
          <verbose>false</verbose>
          <targetClasses>
            <param>org.asynchttpclient*</param>
          </targetClasses>
          <targetTests>
            <param>org.asynchttpclient.*</param>
          </targetTests>
        <excludedTestClasses>
          <param>**/AsyncStreamHandlerTest*</param>
          <param>**/ReactiveStreamsTest*</param>
          <param>**/WebdavTest*</param>
          <param>**/ProxyTest*</param>
        </excludedTestClasses>
          <fullMutationMatrix>true</fullMutationMatrix>
          <exportLineCoverage>true</exportLineCoverage>
          <outputFormats>XML</outputFormats>
        </configuration>
      </plugin>

    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.asynchttpclient</groupId>
      <artifactId>async-http-client-netty-utils</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-codec-http</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-codec-socks</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler-proxy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-epoll</artifactId>
      <classifier>linux-x86_64</classifier>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-kqueue</artifactId>
      <classifier>osx-x86_64</classifier>
    </dependency>
    <dependency>
      <groupId>org.reactivestreams</groupId>
      <artifactId>reactive-streams</artifactId>
    </dependency>
    <dependency>
      <groupId>com.typesafe.netty</groupId>
      <artifactId>netty-reactive-streams</artifactId>
    </dependency>
    <dependency>
      <groupId>io.reactivex.rxjava2</groupId>
      <artifactId>rxjava</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.reactivestreams</groupId>
      <artifactId>reactive-streams-examples</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.kerby</groupId>
      <artifactId>kerb-simplekdc</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
