<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>async-http-client-extras-parent</artifactId>
    <groupId>org.asynchttpclient</groupId>
    <version>2.12.3</version>
  </parent>

  <artifactId>async-http-client-extras-retrofit2</artifactId>
  <name>Asynchronous Http Client Retrofit2 Extras</name>
  <description>The Async Http Client Retrofit2 Extras.</description>

  <properties>
    <retrofit2.version>2.7.2</retrofit2.version>
    <lombok.version>1.18.30</lombok.version>
    <javaModuleName>org.asynchttpclient.extras.retrofit2</javaModuleName>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>${lombok.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>com.squareup.retrofit2</groupId>
      <artifactId>retrofit</artifactId>
      <version>${retrofit2.version}</version>
    </dependency>

    <!-- for tests -->
    <dependency>
      <groupId>com.squareup.retrofit2</groupId>
      <artifactId>converter-scalars</artifactId>
      <version>${retrofit2.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.squareup.retrofit2</groupId>
      <artifactId>converter-jackson</artifactId>
      <version>${retrofit2.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.squareup.retrofit2</groupId>
      <artifactId>adapter-rxjava</artifactId>
      <version>${retrofit2.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.squareup.retrofit2</groupId>
      <artifactId>adapter-rxjava2</artifactId>
      <version>${retrofit2.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

   <build>
    <plugins>
      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <version>1.22.0</version>

        <dependencies>
          <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-testng-plugin</artifactId>
            <version>1.0.0</version>
          </dependency>
        </dependencies>

        <configuration>
          <testPlugin>testng</testPlugin>
          <threads>8</threads>
          <timeoutConstant>1000</timeoutConstant>
          <mutators>
            <mutator>STRONGER</mutator>
          </mutators>
          <avoidCallsTo>
            <avoidCallsTo>java.*</avoidCallsTo>
            <avoidCallsTo>org.apache.log4j</avoidCallsTo>
            <avoidCallsTo>org.slf4j.*</avoidCallsTo>
            <avoidCallsTo>org.apache.commons.logging</avoidCallsTo>
          </avoidCallsTo>
          <verbose>false</verbose>
          <targetClasses>
            <param>org.asynchttpclient.extras.*</param>
          </targetClasses>
          <targetTests>
            <param>org.asynchttpclient.extras.*</param>
          </targetTests>

          <fullMutationMatrix>true</fullMutationMatrix>
          <exportLineCoverage>true</exportLineCoverage>
          <outputFormats>
            <param>XML</param>
          </outputFormats>
        </configuration>
      </plugin>


      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          <encoding>UTF-8</encoding>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>


</project>
