<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.github.scribejava</groupId>
        <artifactId>scribejava</artifactId>
        <version>8.3.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>com.github.scribejava</groupId>
    <artifactId>scribejava-core</artifactId>
    <name>ScribeJava Core</name>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.github.scribejava</groupId>
            <artifactId>scribejava-java8</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.15</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>3.0.1</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version> <!-- the latest for the JRE 7 -->
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <testSourceDirectory>${project.basedir}/${test.dir}/test/java</testSourceDirectory>
        <directory>${project.basedir}/${target.dir}/</directory>

        <plugins>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
        <version>1.22.0</version>
          <configuration>
          <threads>16</threads>

                    <timeoutConstant>8000</timeoutConstant>
                    <mutators>
                        <mutator>STRONGER</mutator>
                    </mutators>
                    <avoidCallsTo>
                        <avoidCallsTo>java.*</avoidCallsTo>
                        <avoidCallsTo>org.apache.log4j</avoidCallsTo>
                        <avoidCallsTo>org.slf4j.*</avoidCallsTo>
                        <avoidCallsTo>org.apache.commons.logging</avoidCallsTo>
                    </avoidCallsTo>
                    <verbose>false</verbose>
                    <targetClasses>
                        <param>com.github.scribejava.core.*</param>
                    </targetClasses>
                    <targetTests>
                        <param>com.github.scribejava.core.*</param>
                    </targetTests>
                    <fullMutationMatrix>true</fullMutationMatrix>
                    <exportLineCoverage>true</exportLineCoverage>
                    <outputFormats>XML</outputFormats>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>testID</id>
            <activation>
                <property>
                    <name>test.dir</name>
                </property>
            </activation>
        </profile>
        <profile>
            <id>targetID</id>
            <activation>
                <property>
                    <name>target.dir</name>
                </property>
            </activation>
        </profile>
    </profiles>
</project>
